version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - doc_container_4-db:/var/lib/postgresql/data

  doc_container_4:
    build:
      context: ./userserver
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  doc_container_3:
    build: ./userapp
    ports:
      - "3000:3000"
    depends_on:
      - doc_container_4

volumes:
  doc_container_4-db:
